### ISSUE TITLE
offline picks

### ISSUE THREAD

**Issue by AchyutPujar** [h-division-2018-2019-even/Repo-13#1]
![excavation functional tree](https://user-images.githubusercontent.com/46969186/52734505-6af87a80-2feb-11e9-9fd8-37cc03f2bce9.jpg)

**Comment by adityakrishnavamsy** [comment]
![function tree](https://user-images.githubusercontent.com/46970931/52772902-af256280-305f-11e9-8e40-9bca1cf3572e.jpg)

**Comment by AchyutPujar** [comment]
![glass](https://user-images.githubusercontent.com/46969186/52774546-78e9e200-3063-11e9-81a4-26e7184b6d47.PNG)

**Comment by adityakrishnavamsy** [comment]
![new doc 2019-02-14 14 08 26_1](https://user-images.githubusercontent.com/46970931/52774693-d8e08880-3063-11e9-8a54-e18e56edf93e.jpg)

![new doc 2019-02-14 14 08 26_2](https://user-images.githubusercontent.com/46970931/52774705-e0a02d00-3063-11e9-892c-0eb31bfed158.jpg)

![new doc 2019-02-14 14 08 26_3](https://user-images.githubusercontent.com/46970931/52774720-eb5ac200-3063-11e9-8c1c-8db299cdb04d.jpg)

![new doc 2019-02-14 14 08 26_4](https://user-images.githubusercontent.com/46970931/52774732-f1e93980-3063-11e9-9602-e0da0444cdf2.jpg)

**Comment by adityakrishnavamsy** [comment]
![WhatsApp Image 2019-03-05 at 23 18 19](https://user-images.githubusercontent.com/46970931/54067936-4f8c3280-426c-11e9-8d10-ecd4d85a372f.jpeg)

**Comment by adityakrishnavamsy** [comment]
![WhatsApp Image 2019-03-05 at 23 18 19](https://user-images.githubusercontent.com/46970931/54067994-186a5100-426d-11e9-88f1-861531da2afd.jpeg)

**Comment by adityakrishnavamsy** [comment]
![correct](https://user-images.githubusercontent.com/46970931/54072049-5f6f3b00-429b-11e9-84d8-9a10b3ebfc00.jpeg)

**Comment by adityakrishnavamsy** [comment]
![servo collection bot ](https://user-images.githubusercontent.com/46970931/54073014-0a85f180-42a8-11e9-8cd6-1cf5e2428baf.jpg)

**Comment by adityakrishnavamsy** [comment]
![locomotion](https://user-images.githubusercontent.com/46970931/54220076-9735e700-4516-11e9-8456-46fa697c498a.jpg)
